### ISSUE TITLE
There are some files that I couldn´t download. Can anyone help please?

### ISSUE THREAD

**Issue by guchaves** [plastic-hub/products#10]
I tried to download the files and some of them  I couldn´t download. Is there any other place where I can have access to it and download?

**Comment by catx23** [comment]
hi, which files are you missing ?

**Comment by guchaves** [comment]
Hi, thanks for getting back to me.

In the shredder V3.2, two files are empty when I open:

   -
      -  sieve_smallplate.sldprt

   mountingplate.x_t.SLDPRT
   - Thank you very much.
   - Best regards,






]



Em dom., 12 de abr. de 2020 às 17:42, catx23 <notifications@github.com>
escreveu:

**Comment by AnneBarbier** [comment]
Hi @guchaves 
alright, yes - sorry this assembly is currently under review and incomplete. I think we complete all this by the end of the week. Sorry for the mess. The laser files however are complete.

How did you find this repository ?

**Comment by catx23** [comment]
@guchaves ,
i've cleaned up the files, a working version is currently in https://github.com/plastic-hub/products/tree/master/products/shredder_v3.2/packed. This design isn't fully tested yet but we receive the parts in the days and let you know.

**Comment by guchaves** [comment]
Thank you so much!

About how I found the repository, the address was in one of the read me
files that you have :)

Thanks again.

Best regards,

Gus

Em seg., 13 de abr. de 2020 às 05:16, Anne Barbier <notifications@github.com>
escreveu:
